# Travis config file to build spk package
# Adapted from https://github.com/torrentalle/spksrc/tree/gogs-build
# And https://github.com/jelmerj/spksrc

# Only build tags
if: tag IS present

# Matrix identical to `all-supported`
env:
  matrix:
    - SYNOARCH=arch-x64-6.1
    - SYNOARCH=arch-x64-5.2
    - SYNOARCH=arch-88f6281-6.1
    - SYNOARCH=arch-alpine-6.1
    - SYNOARCH=arch-armada370-6.1
    - SYNOARCH=arch-armada375-6.1
    - SYNOARCH=arch-armada38x-6.1
    - SYNOARCH=arch-armadaxp-6.1
    - SYNOARCH=arch-comcerto2k-6.1
    - SYNOARCH=arch-denverton-6.1
    - SYNOARCH=arch-evansport-6.1
    - SYNOARCH=arch-hi3535-6.1
    - SYNOARCH=arch-monaco-6.1
    - SYNOARCH=arch-qoriq-6.1
    - SYNOARCH=arch-rtd1296-6.1
    - SYNOARCH=arch-ppc853x-5.2

notifications:
  email: false

# The "sudo: required" image is fastest
sudo: required
dist: trusty

# Output is too verbose for TravisCI, so we hide it
# Remove the ">/dev/null" part to debug!
# make arch-$SYNOARCH always return exit code 0.
# The "ls" line is to test if SPK has been build.

script:
  - PKG=${TRAVIS_TAG%%-*}
  - docker pull synocommunity/spksrc
  - docker run -it -v `pwd`:/spksrc synocommunity/spksrc /bin/bash -c "cd /spksrc && make setup && cd spk/$PKG && make $SYNOARCH>/dev/null"
  - ls packages/*.spk

services:
- docker

git:
  depth: 1

deploy:
  provider: releases
  api_key:
    secure: 0ZfQF4eE613rAGsTvNieRajeyXQEtraEU8QIruONQZBohO74qNWhXWS+xMc6nIAR20h1qxKi2+CT6Kw/S3ec7bCjyS7qTFIlY7vVTY88uLk9omdg1VkPoWsI1Fg4FZvsf8Pyys9R11AugHGOEicdQ2HGJ60ZcmfwwvEshFBu6gn9t0T+ioKbtlGfv/Y1WRXt/T3si0lYe+M+Hsbq9mjZHqVcdcl5/hkANzcwkzrnWpIc1SHyQJZEHd2msnzMo0peZrQn9L24kxnnjlyDaNhwQ5JmE3Td4RlZHYr8ZAdvANGGP1scJ/4sPG9Im9ruKG8X791vCxQp3evQDVqEyeiSmO6GeOp3Q6tAOycHbcXFLLJIRM7L1gI3FHwwmx8H+Pq3DLNgD6oLp/so311VNnVnmlzOULa9V/2r/1JO4JFB0L9LXj/CzQ5NjucICM7XEeBqwlBPFfa8eqObvh4Lo+IdZXqhsFnHaYrsUCzArmqHTLvwBjuiAguEBOeQAbNsXgynTA0xa/AtCXshEFRvog6tva4eowdNCkEonEF7KvycdfR5VkOQWyeKTS2Yh1B9q7B7ffos5lnxLRLKlS5+vNfMwY7La5b+LYQAhhxXzUkaD5KSBRu8Wi92aUSYwHLMCAnreReWugPimYlpeI8eXmp6CYshP6BylmVGGQICS+PQ+hY=
  file_glob: true
  file: packages/*.spk
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
